/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-12 03:45:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._08_005fwebpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import study.model1.helper.PageData;
import java.util.List;
import study.model1.mybatis.service.impl.DepartmentServiceImpl;
import study.model1.mybatis.service.DepartmentService;
import study.model1.mybatis.MybatisConnectionFactory;
import org.apache.ibatis.session.SqlSession;
import study.model1.helper.WebHelper;
import study.model1.mybatis.model.Department;

public final class dept_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("study.model1.helper.PageData");
    _jspx_imports_classes.add("study.model1.mybatis.MybatisConnectionFactory");
    _jspx_imports_classes.add("study.model1.helper.WebHelper");
    _jspx_imports_classes.add("study.model1.mybatis.service.impl.DepartmentServiceImpl");
    _jspx_imports_classes.add("org.apache.ibatis.session.SqlSession");
    _jspx_imports_classes.add("study.model1.mybatis.service.DepartmentService");
    _jspx_imports_classes.add("study.model1.mybatis.model.Department");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	WebHelper webHelper = WebHelper.getInstance(request, response);
	SqlSession sqlSession = MybatisConnectionFactory.getSqlSession();
	DepartmentService departmentService = new DepartmentServiceImpl(sqlSession);

	String keyword = webHelper.getString("keyword", "");
	int nowPage = webHelper.getInt("page", 1);
	int totalCount = 0;
	int listCount = 10;
	int pageCount = 5;
	
	Department input = new Department();
	input.setDname(keyword);
	input.setLoc(keyword);

	List<Department> output = null;
	
	PageData pageData = null;

	try {
		totalCount = departmentService.getDepartmentCount(input);
		pageData = new PageData(nowPage, totalCount, listCount, pageCount);
		Department.setOffset(pageData.getOffset());
		Department.setListCount(pageData.getListCount());
		
		output = departmentService.getDepartmentList(input);
	} catch (Exception e) {
		webHelper.redirect(null, e.getLocalizedMessage());
		sqlSession.close();
		return;
	}
	
	 sqlSession.close();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>학과관리</h1>\r\n");
      out.write("\t<a href=\"dept_add.jsp\">[학과추가]</a>\r\n");
      out.write("\r\n");
      out.write("\t<form method=\"get\" action=\"dept_list.jsp\">\r\n");
      out.write("\t\t<label for=\"keyword\">검색어: </label> \r\n");
      out.write("\t\t<input type=\"search\" name=\"keyword\" id=\"keyword\" placeholder=\"학과명 or 위치 검색\"\r\n");
      out.write("\t\t value=\"");
      out.print(keyword);
      out.write("\" />\r\n");
      out.write("\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"70\" align=\"center\">학과번호</th>\r\n");
      out.write("\t\t\t\t<th width=\"175\" align=\"center\">학과이름</th>\r\n");
      out.write("\t\t\t\t<th width=\"100\" align=\"center\">학과위치</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t");

				if (output.size() == 0) {
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" align=\"center\">조회결과가 없습니다.</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				} else {
					for (Department item : output) {
						int deptno = item.getDeptno();
						String dname = item.getDname();
						String loc = item.getLoc();
						
						if (!keyword.equals("")) {
							dname = dname.replace(keyword, "<mark>" + keyword + "</mark>");
							loc = loc.replace(keyword, "<mark>" + keyword + "</mark>");
						}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">");
      out.print(deptno);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><a href=\"dept_view.jsp?deptno=");
      out.print(deptno);
      out.write('"');
      out.write('>');
      out.print(dname);
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">");
      out.print(loc);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				} //end for
				} //end if
			
      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");

		keyword = URLEncoder.encode(keyword, "utf-8");
		if (pageData.getPrevPage() > 0) {
			String link = String.format("<a href='dept_list.jsp?page=%d&keyword=%s'>[이전]</a>",
			pageData.getPrevPage(), keyword);
			out.println(link);
		} else {
			out.println("[이전]");
		}
		for (int i = pageData.getStartPage(); i <= pageData.getEndPage(); i++) {
			if (i == nowPage) {
				out.println("<strong>[" + i + "]</strong>");
			} else {
				String link = String.format("<a href='dept_list.jsp?page=%d&keyword=%s'>[%d]</a>", i, keyword, i);
				out.println(link);
			}
		}
		if (pageData.getNextPage() > 0) {
			String link = String.format("<a href='dept_list.jsp?page=%d&keyword=%s'>[다음]</a>",
					pageData.getNextPage(), keyword);
			out.println(link);
		} else {
			out.println("[다음]");
		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
